/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author carlos-pc
 */
public class Acciones extends javax.swing.JFrame {

    /**
     * Creates new form Acciones
     */
    public Acciones() {
        initComponents();
        this.setTitle("Acciones");
        imprimirAcciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContenedorAcciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panAcciones = new javax.swing.JPanel();
        lblAcciones = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        cmbAcciones = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panContenedorAcciones.setBackground(new java.awt.Color(204, 204, 255));
        panContenedorAcciones.setAutoscrolls(true);

        jLabel1.setBackground(new java.awt.Color(6, 169, 6));
        jLabel1.setFont(new java.awt.Font("Gautami", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selecciona la opción que realizarás en la biblioteca");
        jLabel1.setOpaque(true);

        panAcciones.setBackground(new java.awt.Color(255, 255, 255));
        panAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true), "Acciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panAcciones.setAutoscrolls(true);
        panAcciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panAcciones.setMaximumSize(new java.awt.Dimension(347, 170));
        panAcciones.setMinimumSize(new java.awt.Dimension(347, 170));

        lblAcciones.setFont(lblAcciones.getFont().deriveFont(lblAcciones.getFont().getStyle() | java.awt.Font.BOLD, lblAcciones.getFont().getSize()+3));
        lblAcciones.setText("Selecciona la acción:");

        btnAceptar.setBackground(new java.awt.Color(0, 103, 36));
        btnAceptar.setFont(btnAceptar.getFont().deriveFont((btnAceptar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        btnAceptar.setForeground(new java.awt.Color(239, 253, 219));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.setBorderPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        cmbAcciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbAcciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAccionesLayout = new javax.swing.GroupLayout(panAcciones);
        panAcciones.setLayout(panAccionesLayout);
        panAccionesLayout.setHorizontalGroup(
            panAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccionesLayout.createSequentialGroup()
                .addGroup(panAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAccionesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblAcciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAccionesLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAccionesLayout.setVerticalGroup(
            panAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcciones)
                    .addComponent(cmbAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout panContenedorAccionesLayout = new javax.swing.GroupLayout(panContenedorAcciones);
        panContenedorAcciones.setLayout(panContenedorAccionesLayout);
        panContenedorAccionesLayout.setHorizontalGroup(
            panContenedorAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panContenedorAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panContenedorAccionesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panContenedorAccionesLayout.setVerticalGroup(
            panContenedorAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(panAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContenedorAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContenedorAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        String co=Integer.toString((int)cmbAcciones.getSelectedItem());
        
        if(co!=null){
            OtraAccion otraAccion=new OtraAccion();
            otraAccion.setVisible(true);
            otraAccion.setLocationRelativeTo(null);
            hide();
        }
        else{
            JOptionPane.showMessageDialog(null,"Debes de seleccionar una acción");
        }
            
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccionesActionPerformed
        
    }//GEN-LAST:event_cmbAccionesActionPerformed
    
    private void imprimirAcciones(){
        javax.swing.DefaultComboBoxModel modeloCombo = new javax.swing.DefaultComboBoxModel();
        for(int i=0;i<5;i++){
            modeloCombo.addElement(i);
        }
        cmbAcciones.setModel(modeloCombo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cmbAcciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JPanel panAcciones;
    private javax.swing.JPanel panContenedorAcciones;
    // End of variables declaration//GEN-END:variables
}
