/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author carlos-pc
 */
public class ConsultarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarUsuarios
     */
    public ConsultarUsuario() {
        initComponents();
        this.setTitle("Consultar usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panContenedorConsultarUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panOpcionesBusqueda = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnApellido = new javax.swing.JRadioButton();
        rbtnClave = new javax.swing.JRadioButton();
        rbtnMatricula = new javax.swing.JRadioButton();
        rbtnTodos = new javax.swing.JRadioButton();
        btnBusqueda = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        lblBusqueda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panContenedorConsultarUsuario.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(6, 169, 6));
        jLabel1.setFont(new java.awt.Font("Gautami", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Selecciona la forma de buscar al USUARIO ");
        jLabel1.setOpaque(true);

        panOpcionesBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panOpcionesBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true), "Opciones de búsqueda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panOpcionesBusqueda.setAutoscrolls(true);
        panOpcionesBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panOpcionesBusqueda.setMaximumSize(new java.awt.Dimension(360, 195));
        panOpcionesBusqueda.setMinimumSize(new java.awt.Dimension(360, 195));

        btnRegresar.setBackground(new java.awt.Color(167, 167, 206));
        btnRegresar.setFont(btnRegresar.getFont().deriveFont((btnRegresar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnNombre);
        rbtnNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnNombre.setSelected(true);
        rbtnNombre.setText("Por nombre");
        rbtnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnApellido);
        rbtnApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnApellido.setText("Por apellido");
        rbtnApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnApellidoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnClave);
        rbtnClave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnClave.setText("Por clave");
        rbtnClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClaveActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnMatricula);
        rbtnMatricula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnMatricula.setText("Por matricula");
        rbtnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMatriculaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTodos);
        rbtnTodos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnTodos.setText("Mostrar todos");
        rbtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTodosActionPerformed(evt);
            }
        });

        btnBusqueda.setBackground(new java.awt.Color(0, 103, 36));
        btnBusqueda.setFont(btnBusqueda.getFont().deriveFont((btnBusqueda.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        btnBusqueda.setForeground(new java.awt.Color(239, 253, 219));
        btnBusqueda.setText("Buscar");
        btnBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBusqueda.setBorderPainted(false);
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        txtBusqueda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblBusqueda.setFont(lblBusqueda.getFont().deriveFont(lblBusqueda.getFont().getStyle() | java.awt.Font.BOLD, lblBusqueda.getFont().getSize()+3));
        lblBusqueda.setText("Introduce el nombre:");

        javax.swing.GroupLayout panOpcionesBusquedaLayout = new javax.swing.GroupLayout(panOpcionesBusqueda);
        panOpcionesBusqueda.setLayout(panOpcionesBusquedaLayout);
        panOpcionesBusquedaLayout.setHorizontalGroup(
            panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                        .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                                        .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnNombre)
                                            .addComponent(rbtnClave))
                                        .addGap(18, 18, 18)
                                        .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnMatricula)
                                            .addComponent(rbtnApellido)))
                                    .addComponent(rbtnTodos)))
                            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBusqueda))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panOpcionesBusquedaLayout.setVerticalGroup(
            panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnNombre)
                    .addComponent(rbtnApellido))
                .addGap(18, 18, 18)
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnClave)
                    .addComponent(rbtnMatricula))
                .addGap(18, 18, 18)
                .addComponent(rbtnTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panContenedorConsultarUsuarioLayout = new javax.swing.GroupLayout(panContenedorConsultarUsuario);
        panContenedorConsultarUsuario.setLayout(panContenedorConsultarUsuarioLayout);
        panContenedorConsultarUsuarioLayout.setHorizontalGroup(
            panContenedorConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorConsultarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panContenedorConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panOpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panContenedorConsultarUsuarioLayout.setVerticalGroup(
            panContenedorConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorConsultarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panOpcionesBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContenedorConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panContenedorConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ConsultarOpciones consultar=new ConsultarOpciones();
        consultar.setVisible(true);
        consultar.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void rbtnClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClaveActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnClaveActionPerformed

    private void rbtnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMatriculaActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnMatriculaActionPerformed

    private void rbtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTodosActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnTodosActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        ResulBusquedaUsuarios busqueda=new ResulBusquedaUsuarios();
        busqueda.setVisible(true);
        busqueda.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void rbtnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNombreActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnNombreActionPerformed

    private void rbtnApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnApellidoActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnApellidoActionPerformed

    public void tipoBusqueda(){
        if(rbtnNombre.isSelected()==true){
            lblBusqueda.setText("Introduce el nombre:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnApellido.isSelected()==true){
            lblBusqueda.setText("Introduce el apellido:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnClave.isSelected()==true){
            lblBusqueda.setText("Introduce la clave del usuario:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnMatricula.isSelected()==true){
            lblBusqueda.setText("Introduce la matricula del usuario:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnTodos.isSelected()==true){
            lblBusqueda.setText("Encontrar todos los usuarios");
            lblBusqueda.disable();
            txtBusqueda.disable();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JPanel panContenedorConsultarUsuario;
    private javax.swing.JPanel panOpcionesBusqueda;
    private javax.swing.JRadioButton rbtnApellido;
    private javax.swing.JRadioButton rbtnClave;
    private javax.swing.JRadioButton rbtnMatricula;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JRadioButton rbtnTodos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
