/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author carlos-pc
 */
public class ConsultarLibro extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarLibro
     */
    public ConsultarLibro() {
        initComponents();
        this.setTitle("Consultar libro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panContenedorConsultarLibro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panOpcionesBusqueda = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        rbtnTitulo = new javax.swing.JRadioButton();
        rbtnAutor = new javax.swing.JRadioButton();
        rbtnISBN = new javax.swing.JRadioButton();
        rbtnFolio = new javax.swing.JRadioButton();
        rbtnSignatura = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        lblBusqueda = new javax.swing.JLabel();
        rbtnTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panContenedorConsultarLibro.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(6, 169, 6));
        jLabel1.setFont(new java.awt.Font("Gautami", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Selecciona la forma de buscar al LIBRO ");
        jLabel1.setOpaque(true);

        panOpcionesBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panOpcionesBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true), "Opciones de búsqueda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panOpcionesBusqueda.setAutoscrolls(true);
        panOpcionesBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panOpcionesBusqueda.setMaximumSize(new java.awt.Dimension(360, 195));
        panOpcionesBusqueda.setMinimumSize(new java.awt.Dimension(360, 195));

        btnRegresar.setBackground(new java.awt.Color(167, 167, 206));
        btnRegresar.setFont(btnRegresar.getFont().deriveFont((btnRegresar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTitulo);
        rbtnTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnTitulo.setSelected(true);
        rbtnTitulo.setText("Por título");
        rbtnTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTituloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnAutor);
        rbtnAutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnAutor.setText("Por autor");
        rbtnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAutorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnISBN);
        rbtnISBN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnISBN.setText("Por ISBN");
        rbtnISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnISBNActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnFolio);
        rbtnFolio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnFolio.setText("Por folio");
        rbtnFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFolioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnSignatura);
        rbtnSignatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnSignatura.setText("Signatura");
        rbtnSignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSignaturaActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 103, 36));
        btnBuscar.setFont(btnBuscar.getFont().deriveFont((btnBuscar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        btnBuscar.setForeground(new java.awt.Color(239, 253, 219));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setBorderPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBusqueda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblBusqueda.setFont(lblBusqueda.getFont().deriveFont(lblBusqueda.getFont().getStyle() | java.awt.Font.BOLD, lblBusqueda.getFont().getSize()+3));
        lblBusqueda.setText("Introduce el nombre:");

        buttonGroup1.add(rbtnTodos);
        rbtnTodos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnTodos.setText("Mostrar todos");
        rbtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOpcionesBusquedaLayout = new javax.swing.GroupLayout(panOpcionesBusqueda);
        panOpcionesBusqueda.setLayout(panOpcionesBusquedaLayout);
        panOpcionesBusquedaLayout.setHorizontalGroup(
            panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                        .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnTitulo)
                                    .addComponent(rbtnISBN)
                                    .addComponent(rbtnSignatura))
                                .addGap(32, 32, 32)
                                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnTodos)
                                    .addComponent(rbtnFolio)
                                    .addComponent(rbtnAutor)))
                            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBusqueda))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panOpcionesBusquedaLayout.setVerticalGroup(
            panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpcionesBusquedaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTitulo)
                    .addComponent(rbtnAutor))
                .addGap(18, 18, 18)
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnISBN)
                    .addComponent(rbtnFolio))
                .addGap(18, 18, 18)
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSignatura)
                    .addComponent(rbtnTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panContenedorConsultarLibroLayout = new javax.swing.GroupLayout(panContenedorConsultarLibro);
        panContenedorConsultarLibro.setLayout(panContenedorConsultarLibroLayout);
        panContenedorConsultarLibroLayout.setHorizontalGroup(
            panContenedorConsultarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorConsultarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panContenedorConsultarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panOpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panContenedorConsultarLibroLayout.setVerticalGroup(
            panContenedorConsultarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorConsultarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panOpcionesBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panContenedorConsultarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panContenedorConsultarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ConsultarOpciones consultar=new ConsultarOpciones();
        consultar.setVisible(true);
        consultar.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void rbtnTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTituloActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnTituloActionPerformed

    private void rbtnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAutorActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnAutorActionPerformed

    private void rbtnISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnISBNActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnISBNActionPerformed

    private void rbtnFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFolioActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnFolioActionPerformed

    private void rbtnSignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSignaturaActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnSignaturaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ResulBusquedaLibros busqueda=new ResulBusquedaLibros();
        busqueda.setVisible(true);
        busqueda.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTodosActionPerformed
        tipoBusqueda();
    }//GEN-LAST:event_rbtnTodosActionPerformed
    
    public void tipoBusqueda(){
        if(rbtnTitulo.isSelected()==true){
            lblBusqueda.setText("Introduce el título del libro:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnAutor.isSelected()==true){
            lblBusqueda.setText("Introduce el nombre del autor:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnISBN.isSelected()==true){
            lblBusqueda.setText("Introduce el ISBN:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnFolio.isSelected()==true){
            lblBusqueda.setText("Introduce el número de folio:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnSignatura.isSelected()==true){
            lblBusqueda.setText("Introduce la signatura del libro:");
            lblBusqueda.enable();
            txtBusqueda.enable();
        }
        if(rbtnTodos.isSelected()==true){
            lblBusqueda.setText("Encontrar todos los libros");
            lblBusqueda.disable();
            txtBusqueda.disable();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JPanel panContenedorConsultarLibro;
    private javax.swing.JPanel panOpcionesBusqueda;
    private javax.swing.JRadioButton rbtnAutor;
    private javax.swing.JRadioButton rbtnFolio;
    private javax.swing.JRadioButton rbtnISBN;
    private javax.swing.JRadioButton rbtnSignatura;
    private javax.swing.JRadioButton rbtnTitulo;
    private javax.swing.JRadioButton rbtnTodos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
