/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author carlos-pc
 */
public class ResulBusquedaUsuarios extends javax.swing.JFrame {

    private int fila, cols, fils;
    Object[] columnas = new Object[4];
    Object dato;
    String valor;
    javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel();
    public ResulBusquedaUsuarios() {
        initComponents();
        this.setTitle("Resultados de búsqueda de usuarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContenedorUsuarios = new javax.swing.JPanel();
        lblBusquedaNombre = new javax.swing.JLabel();
        panUsuarios = new javax.swing.JPanel();
        btnAcceder = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblUsuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panContenedorUsuarios.setBackground(new java.awt.Color(204, 204, 255));
        panContenedorUsuarios.setAutoscrolls(true);

        lblBusquedaNombre.setBackground(new java.awt.Color(6, 169, 6));
        lblBusquedaNombre.setFont(new java.awt.Font("Gautami", 1, 16)); // NOI18N
        lblBusquedaNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblBusquedaNombre.setText(" Tabla con los usuarios encontrados ");
        lblBusquedaNombre.setOpaque(true);

        panUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        panUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panUsuarios.setAutoscrolls(true);
        panUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panUsuarios.setMaximumSize(new java.awt.Dimension(347, 170));
        panUsuarios.setMinimumSize(new java.awt.Dimension(347, 170));

        btnAcceder.setBackground(new java.awt.Color(0, 103, 36));
        btnAcceder.setFont(btnAcceder.getFont().deriveFont((btnAcceder.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        btnAcceder.setForeground(new java.awt.Color(239, 253, 219));
        btnAcceder.setText("Acceder");
        btnAcceder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAcceder.setBorderPainted(false);
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(167, 167, 206));
        btnRegresar.setFont(btnRegresar.getFont().deriveFont((btnRegresar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblUsuarios.setFont(lblUsuarios.getFont().deriveFont(lblUsuarios.getFont().getStyle() | java.awt.Font.BOLD, lblUsuarios.getFont().getSize()+3));
        lblUsuarios.setText("Selecciona un usuario para acceder a sus propiedades");

        tblUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"100", null, null, "55555"},
                {"123", "2", null, "12334"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombres", "Apellidos", "Matricula"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setMinWidth(50);
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(60);
            tblUsuarios.getColumnModel().getColumn(3).setMinWidth(120);
            tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblUsuarios.getColumnModel().getColumn(3).setMaxWidth(140);
        }

        javax.swing.GroupLayout panUsuariosLayout = new javax.swing.GroupLayout(panUsuarios);
        panUsuarios.setLayout(panUsuariosLayout);
        panUsuariosLayout.setHorizontalGroup(
            panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuariosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panUsuariosLayout.createSequentialGroup()
                        .addComponent(btnAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUsuarios)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panUsuariosLayout.setVerticalGroup(
            panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panContenedorUsuariosLayout = new javax.swing.GroupLayout(panContenedorUsuarios);
        panContenedorUsuarios.setLayout(panContenedorUsuariosLayout);
        panContenedorUsuariosLayout.setHorizontalGroup(
            panContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblBusquedaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panContenedorUsuariosLayout.setVerticalGroup(
            panContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBusquedaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContenedorUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panContenedorUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        /*//if(fila==1){//Comparamos si la fila seleccionada es la 0, es decir la primera
            JOptionPane.showMessageDialog(null,"Si se cumple tu condición"+valor);
        //}*/
        DatosUsuarios datos=new DatosUsuarios();
        datos.setVisible(true);
        datos.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ConsultarUsuario consultar=new ConsultarUsuario();
        consultar.setVisible(true);
        consultar.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        fila=tblUsuarios.rowAtPoint(evt.getPoint());//Recibe el número de fila seleccionada
        
        recuperarDatos();//De la fila seleccionada, recupera el valor
                                            //de la columna 3, es decir la clave
                                            //del usuario seleccionado
    }//GEN-LAST:event_tblUsuariosMouseClicked
    
    public String recuperarDatos(){
        dato=tblUsuarios.getValueAt(fila,0);
        valor=String.valueOf(dato);
        return (valor);
    }
    void detDatos(){
        /*tring AInteres="";
        filas[0] = txtNombre.getText();//carga el nombre
        filas[1] = txtApellidos.getText();//carga el apellido
        filas[2] = cmbAnyos.getSelectedItem().toString();//carga el año de nacimiento
        filas[3] = lblEdad.getText();//carga la edad
        if(rdMasculino.isSelected()){filas[4]="Masculino";}//si es masculino
        else{filas[4]="Femenino";}//o si es femenino
        if(chkFutbol.isSelected()) AInteres=chkFutbol.getText()+",";
        if(chkVolleyball.isSelected()) AInteres= AInteres + chkVolleyball.getText()+",";
        if(chkOtro.isSelected()) AInteres = AInteres + txtOtro.getText();
        filas[5] = AInteres;*/
        
    }
    public void tipoBusqueda(){
    }/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResulBusquedaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResulBusquedaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResulBusquedaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResulBusquedaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResulBusquedaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusquedaNombre;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel panContenedorUsuarios;
    private javax.swing.JPanel panUsuarios;
    public javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
